name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install protoc
      run: |
        # TODO: cache
        wget https://github.com/protocolbuffers/protobuf/releases/download/v21.5/protoc-21.5-linux-x86_64.zip
        unzip protoc-21.5-linux-x86_64.zip
        sudo mv ./bin/protoc /usr/local/bin/
        rm -rf protoc-21.5-linux-x86_64.zip include readme.txt
    - name: Run tests
      run: cargo test --verbose
